### PR TITLE
Make fields configurable

### LINKED ISSUE #18: Allow hiding fields by configuration
Would you accept a pull request for configuring the fields shown on checkout via store config or do you strongly recommend to fork and customize for the use case instead?

### PR DESCRIPTION
**Pull request by kolaente**
This PR adds the ability to enable/disable fields per store view in the admin interface.

Resolves #18

### CODE REVIEW

**Comment by amenk** [comment]
screenshot_auswahl_014
Strange positioning ... I think it should be before or after shipping method

**Comment by kolaente** [comment]
@amenk Maybe this is because of some custom xml? I'm not sure if the positioning is a consequence of my pr. Did you test with the base module?

**Comment by amenk** [comment]
Good catch ! The dev-master has the same problem. I will debug

**Comment by kolaente** [comment]
@sbodak Would you mind reviewing?

**Comment by sbodak** [comment]
@kolaente Please read my explanation here
https://github.com/sbodak/magento2-checkout-custom-form/issues/18#issuecomment-473014488

**Pull request closed without merging**
